---
title: ¡Bienvenidos a mi sitio personal!
author: ''
date: '2020-07-23'
slug: bienvenidos-a-mi-website
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-07-23T16:00:48-03:00'
featured: true
image:
  caption: 'Créditos: [**Getty Images**](http://www.gettyimages.es/detail/1143248561)'
  focal_point: ''
  preview_only: no
projects: []
links:
  - icon_pack: fab
    icon: twitter
    name: Seguir
    url: 'https://twitter.com/Mauricio_Cely'
output: 
  blogdown::html_page:
      highlight: pygments
      toc: true
      toc_depth: 2
# header-includes:
  # - \usepackage{cancel}
---

He comenzado este blog para abordar varios conceptos de Matemáticas, Física, Ciencia y programación usando <i class = "fab fa-r-project" style = "color: #4475a0"></i>. La idea es compartir algo de lo poco que conozco al respecto, espero que también les sea útil a ustedes.

Mi primer contacto con R comenzó cuando comencé mi maestría en Física (2016), no sabía nada sobre programación. En el laboratorio donde trabajaba, todos usaban R o MATLAB, tenìa que elegir uno, un amigo me animó y me ayudó con algunos tutoriales básicos en R. Al principio fue difícil, pero después de algún tiempo entendí lo útil y divertido que sería aprender. Ahora es la herramienta que uso para todo. Espero que la información de este blog te ayude a resolver tus dificultades. Pueden encontrarme en [mauriciocelytoro@hotmail.com](mailto: mauriciocelytoro@hotmail.com) donde con certeza responderé todos sus correos electrónicos. Todos sus comentarios son más que bienvenidos.

Gracias a todos los que pasaron su tiempo leyendo mis *publicaciones*.
