---
title: Welcome to my website !!!
author: ''
date: '2020-07-23'
slug: welcome-to-my-website
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-07-23T16:00:48-03:00'
featured: true
image:
  caption: 'Image credit: [**Getty Images**](http://www.gettyimages.es/detail/1143248561)'
  focal_point: ''
  preview_only: no
projects: []
links:
  - icon_pack: fab
    icon: twitter
    name: Follow
    url: 'https://twitter.com/Mauricio_Cely'
output: 
  blogdown::html_page:
      highlight: pygments
      toc: true
      toc_depth: 2
# header-includes:
  # - \usepackage{cancel}
---

Hello everybody and welcome to my brand new website! First of all excuse me for the writing - English is not my native language - but if you have a question does not doubt to write me. I have started this blog to tackle through various concepts of Mathematics, Physics, Science and programming using <i class="fab fa-r-project" style="color:#4475a0"></i>. The idea is to share some of my knowledge I have about it hopefully it will be useful to you too.

My first contact with R began when I started my master degree in Physics (2016), I did not know anything about programming. In the lab where I worked they all used R or MATLAB, I had to choose one, a friend encourage and help me with some basic tutorials in R. At the beginning it was difficult but then I understood the useful and fun it will be to learn. Now it is the tool I use for everything. I hope the info in this blog help you to solve your difficulties. You can find me in [mauriciocelytoro@hotmail.com](mailto:mauriciocelytoro@hotmail.com) where I will answer all your emails for sure. All your comments are more than welcome.

Thanks to all of you who spend your time reading my *posts*.